TPC.Web/Controllers/TCPControllers/FAQController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TPC.Core;
using TPC.Core.Interfaces;
using TPC.Web.Filters;

namespace TPC.Web.Controllers.TCPControllers
{

    public class FAQController : BaseController
    {
         private readonly IFAQService _faqsrv;

         public FAQController(FAQService faqSrv)
        {
            _faqsrv = faqSrv;
            _faqsrv.UserVM = UserVM;

        }

         public ActionResult Index()
         {
             return View();
         }

         public ActionResult FAQ()
         {
             _faqsrv.UserVM = UserVM;
             return View("../TCPViews/FAQ",_faqsrv.GetDetails());
         }
    }
}

TPC.Web/Controllers/TCPControllers/ItemGroupingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TPC.Core.Models;
using TPC.Web.Filters;
using TPC.Core;
using TPC.Core.Interfaces;
using Microsoft.Practices.Unity;
using TPC.Core.Models.ViewModels;
using System.Web.Security;

namespace TPC.Web.Controllers.TCPControllers
{
        [TPCAuthorize]
    public class ItemGroupingController : BaseController
    {
        //
        // GET: /ItemGrouping/
       public readonly IItemGroupingService _iItemGroupingService;
       public ItemGroupingController(ItemGroupingService itemGroupingService)
        {
            _iItemGroupingService = itemGroupingService;
            _iItemGroupingService.UserVM = UserVM;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetListOfItems(string itemID)
        {
            ItemGroupingViewModel itemGroupingViewModel = new ItemGroupingViewModel();
            itemGroupingViewModel =  _iItemGroupingService.GetItemsList(itemID);
            itemGroupingViewModel.UserVM = UserVM;
            return View("../TCPViews/ItemGrouping", itemGroupingViewModel);
        }
        public ActionResult AddNewGroupType(string groupType,string itemID)
        {
            _iItemGroupingService.AddNewGroupType(groupType);
            return View("../TCPViews/ItemGrouping",_iItemGroupingService.GetItemsList(itemID));
        }
        public ActionResult AddGroupParentage(string childGroupID, string parentGroupID)
        {
            return View("../TCPViews/ItemGrouping", _iItemGroupingService.AddGroupParentage(Convert.ToInt32(childGroupID),Convert.ToInt32(parentGroupID)));
        }

    }
}

TPC.Web/Controllers/TCPControllers/ItemListViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TPC.Core.Models;
using TPC.Web.Filters;
using TPC.Core;
using TPC.Core.Interfaces;
using Microsoft.Practices.Unity;
using TPC.Core.Models.ViewModels;
using System.Web.Security;
using System.Web.UI;
using WebMatrix.WebData;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System.Configuration;
using System.Text;
using TPC.Common.Enumerations;
using System.Diagnostics;
using TPC.Web.Infrastructure;

namespace TPC.Web.Controllers.TCPControllers
{
    [TPCAuthorize]

    public class ItemListViewController : BaseController
    {
        //
        // GET: /ItemListView/

        public readonly IItemListViewService _iItemListViewService;

        public IItemService _itemservice;
        QuoteViewService _quoteViewService = new QuoteViewService();

        public ItemListViewController(ItemListViewService itemListViewService)
        {
            _iItemListViewService = itemListViewService;
            _itemservice = new ItemService();
            _itemservice.UserVM = UserVM;
        }

        public ActionResult Index()
        {
            return View();
        }



        [HttpPost]
        [AllowAnonymous]
        public ActionResult ViewSingleItem(string itemID, string QuoteID, string type = "")
        {
            _itemservice.UserVM = UserVM;
            if (WebSecurity.IsAuthenticated)
            {
                _quoteViewService.UserVM = UserVM;
                UserVM.CurrentQuoteID = QuoteID != "0" ? Convert.ToInt32(QuoteID) : _quoteViewService.getCustomerSCQuoteID();
            }
            ItemDetailedViewModel itDVM = _itemservice.GetItemByID(itemID, QuoteID, type);
            this.AssignUserVM(_itemservice.UserVM);
            return PartialView("../TCPViews/Partial/ItemDetailedPartial", itDVM);
        }
        //to view popup in singleItemDetailedView

        [HttpPost]
        public ActionResult ViewSingleItemByISBN(string ISBN, string QuoteID)
        {
            //string lstItemIds = _itemservice.GetItemIDsListByIsbn(ISBN, QuoteID);
            _itemservice.UserVM = UserVM;
            //  if (lstItemIds != null && lstItemIds != string.Empty)
            // {
            //     _itemservice.selectedOptions(lstItemIds, QuoteID, WebSecurity.CurrentUserId);
            //  }
            ItemDetailedViewModel itemDVM = _itemservice.GetItemByISBN(ISBN, QuoteID);
            //  itemDVM.UserVM = UserVM;
            //  this.AssignUserVM(_itemservice.UserVM);
            if (itemDVM.ItemID != null)
            {
                return PartialView("../TCPViews/Partial/ItemDetailedPartial", itemDVM);
            }
            else
            {
                return null;
            }
        }


        [HttpPost]
        public ActionResult ViewSingleDetailedParialView(string itemID, string QuoteID, string type = "")
        {
            _itemservice.UserVM = UserVM;
            ItemDetailedViewModel itemDVM = _itemservice.GetItemByID(itemID, QuoteID, type);
            itemDVM.UserVM = UserVM;
            return PartialView("../TCPViews/Partial/SingleItemDetailPartial", itemDVM);
        }
        //showing pdf and downloading excel
        [AllowAnonymous]
        public ActionResult ViewListOfItems()
        {

            int quoteID = Convert.ToInt32(Request.QueryString["quoteDWID"]);
            bool isPdf = Convert.ToBoolean(Request.QueryString["isPdf"]);
            bool invoicePdf = Convert.ToBoolean(Request.QueryString["invoicePdf"]);
            bool isExcel = Convert.ToBoolean(Request.QueryString["isExcel"]);

            if (isPdf || isExcel)
            {
                ActiveQuoteService _activeQuoteSrv = new ActiveQuoteService();
                _activeQuoteSrv.UserVM = UserVM != null ? UserVM : null;
                OrderViewModel orderVM = _activeQuoteSrv.GeneratePDF(quoteID);
                orderVM.InvoiceModel.FederalID = ConfigurationManager.AppSettings["FederalID"];
                var pdf = new RazorPDF.PdfResult(orderVM, "../TCPViews/GeneratePDF");
                if (isExcel)
                {
                    StringBuilder sb = new StringBuilder();
                    string headerText = string.Format(Resources.TCPResources.QuoteEmailExcelHeaderTable, ConfigurationManager.AppSettings["imgLogoPath"], string.Format("{0:d}", DateTime.Today), orderVM.QuoteID, orderVM.CustNumber, orderVM.RepoAddress.RepName, orderVM.CustomerName, orderVM.RepoAddress.RepEmail, orderVM.RepoAddress.CustFirstName + ' ' + orderVM.RepoAddress.CustLastName);
                    sb.Append(headerText);
                    sb.Append(ConvertToString(orderVM.CartListView));
                    double totalPrice = orderVM.CartListView.Sum(e => e.Price);
                    double taxPrice = 0;
                    if (orderVM.SalesTax > 0)
                    {
                        taxPrice = (totalPrice * (double)orderVM.SalesTax);
                    }
                    string footerText = string.Format(Resources.TCPResources.QuoteEmailExcelFooterTable, String.Format("{0:C}", taxPrice + totalPrice), String.Format("{0:C}", orderVM.ShippingCharge), String.Format("{0:C}", taxPrice + totalPrice));
                    sb.Append(footerText);
                    byte[] buffer = System.Text.Encoding.UTF8.GetBytes(sb.ToString());
                    Response.AddHeader("Content-Disposition", "attachment; filename=" + orderVM.CustNumber + "_" + orderVM.QuoteID + ".xls");
                    Response.ContentType = "application//vnd.ms-excel";
                    Response.Buffer = true;
                    Response.Cache.SetCacheability(HttpCacheability.NoCache);
                    Response.BinaryWrite(buffer);
                    Response.End();
                    Response.Close();
                }
                else if (isPdf)
                {
                    orderVM.Type = "Export";

                    //added by faraaz
                    if (invoicePdf)
                        orderVM.Type = "invoicePdf";

                    Response.ContentType = "application/pdf";
                    if (invoicePdf)
                        Response.AddHeader("Content-Disposition", "inline;" + orderVM.CustNumber + "_" + orderVM.QuoteID + ".pdf");
                    else
                        Response.AddHeader("Content-Disposition", "attachment;" + orderVM.CustNumber + "_" + orderVM.QuoteID + ".pdf");
                }
                pdf.ViewBag.Title = "Report Title";
                return pdf;
            }
            else
            {
                _iItemListViewService.UserVM = UserVM;
                ItemListViewModel itemVM = _iItemListViewService.GetListOfItems(Convert.ToInt32(Request.QueryString["quoteDWID"]), "", "30", 1, "");
                this.AssignUserVM(_iItemListViewService.UserVM);
                ViewData["QuoteType"] = itemVM.QuoteType;
                ViewData["QuoteTitle"] = itemVM.QuoteTitle;
                return View("../TCPViews/ItemListView", itemVM);
            }

        }
        private StringBuilder ConvertToString<T>(IList<T> data)
        {
            System.ComponentModel.PropertyDescriptorCollection properties =
              System.ComponentModel.TypeDescriptor.GetProperties(typeof(T));
            StringBuilder sb = new StringBuilder();
            List<PropertyInfo> property = typeof(T).GetProperties().ToList();
            var lstOrderList = property.Where(e => ((DisplayAttribute)e.GetCustomAttributes(typeof(DisplayAttribute), false).FirstOrDefault()) != null && ((DisplayAttribute)e.GetCustomAttributes(typeof(DisplayAttribute), false).FirstOrDefault()).Order != -1).OrderBy(e => ((DisplayAttribute)e.GetCustomAttributes(typeof(DisplayAttribute), false).FirstOrDefault()).Order).ToList();
            sb.Append("<table style=\"border-collapse:collapse;text-align:left\">");
            //write column headings
            sb.Append("<tr>");
            foreach (var prop in lstOrderList)
                if (prop.Name != "AcRcLevelText")
                    sb.Append("<td><b><font face=Arial size=" + "10px" + ">" + prop.Name + "</font></b></td>");
                else
                    sb.Append("<td><b><font face=Arial size=" + "10px" + "></font></b></td>");
            sb.Append("</tr>");
            foreach (T item in data)
            {
                sb.Append("<tr>");
                foreach (var prop in lstOrderList)
                    sb.Append("<td><font face=Arial size=" + "10px" + ">" + prop.GetValue(item) + "&nbsp; </font></td>");
                sb.Append("</tr>");
            }
            return sb;
        }
        [HttpPost]

        public ActionResult ViewSearchSingleItem(string itemID, string QuoteID, string SearchType)
        {
            ViewData["SearchCategory"] = SearchType;
            return PartialView("../TCPViews/Partial/ItemDetailedPartial", _itemservice.GetItemByID(itemID, QuoteID));
        }

        [HttpPost]
        public ActionResult selectedItem(string selectbtnid, string itemID, string quoteID, string ViewName = "")
        {
            _itemservice.UserVM = UserVM;
            _itemservice.selectedOptions(itemID, quoteID, WebSecurity.CurrentUserId);
            this.AssignUserVM(_itemservice.UserVM);
            return View("../TCPViews/ItemListDetailedView", _itemservice.GetItemListDetailByID(itemID, quoteID));
        }

        [HttpPost]
        public JsonResult UpdateStatusofAllItems(string selectbtnid, string itemID, string quoteID, string type = "")
        {
            _itemservice.UserVM = UserVM;
            ItemListViewModel itemListVM = _itemservice.selectedOptions(itemID, quoteID, WebSecurity.CurrentUserId, type);
            this.AssignUserVM(_itemservice.UserVM);
            return Json(itemListVM);
        }

        [HttpPost]
        public JsonResult AddCollectionsToQuotDWCartbyGroupID(int groupID, string quoteID, string selectedFilters)

TPC.Web/Controllers/TCPControllers/LibrarianResourcesController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TPC.Core;
using TPC.Core.Interfaces;
using TPC.Web.Filters;

namespace TPC.Web.Controllers.TCPControllers
{

    [AllowAnonymous]
    public class LibrarianResourcesController : BaseController
    {
        private readonly ILibrarianResourcesService _librarianresources;
        public LibrarianResourcesController(LibrarianResourcesService librarianresources)
        {
            _librarianresources = librarianresources;

            _librarianresources.UserVM = UserVM;
        }

        public ActionResult Librarian()
        {
            _librarianresources.UserVM = UserVM;
            return View("../TCPViews/LibrarianResources", _librarianresources.GetLibraryResource());
        }

        //  [HttpPost]
        public FileResult pdfLoad(string path)
        {
            string pdfpath = path.Replace(".jpg", ".pdf");
            Stream fReadstreal = System.IO.File.OpenRead(pdfpath);
            byte[] bte = new byte[fReadstreal.Length];
            int ofst = 0;
            fReadstreal.Read(bte, ofst, bte.Length);
            fReadstreal.Close();
            Response.ClearContent();
            Response.ClearHeaders();
            Response.BinaryWrite(bte);
            Response.AddHeader("Content-Disposition", "inline;filename=" + "Libarary.pdf");
            Response.ContentType = "application/pdf";
            Response.Flush();
            Response.Clear();
            Response.End();
            return null;
        }

        //public ActionResult GetImage(string imgPath)
        //{
        //    return File(imgPath, "image/jpeg");
        //}

        public ActionResult GetPdf(string pdfPath)
        {
            return File(pdfPath, "application/pdf");
        }
    }
}

TPC.Web/Views/TCPViews/CategoriesItemContainer.cshtml
@using TPC.Common.Enumerations;
@model TPC.Core.Models.ViewModels.CategoriesItemContainerViewModel
@{
    string SCItemsCount = "";
    if (@Model.UserVM != null)
    {
        SCItemsCount = Model.UserVM.SCCount.ToString();

    }

    if (Roles.IsUserInRole(UserRolesEnum.CustomerShipTo.ToString()) || !WebSecurity.IsAuthenticated)
    {
        ViewBag.Title = "Products";
    }
    else
    {
        if (Model.CategoriesPVM.ItemGroupVM.GroupID == 0)
        {
            ViewBag.Title = "Search";
        }
        else
        {
            ViewBag.Title = "Categories";
        }
    }
    Layout = "~/Views/Shared/PenworthyLayout.cshtml";
}
@using TPC.Core.Models;
@using TPC.Core.Models.Models;
@using TPC.Core.Models.ViewModels;
@using TPC.Common.Enumerations;
@{
    List<ItemViewModel> lstItemVM = new List<ItemViewModel>();
    ItemParentViewModel itemPVM = new ItemParentViewModel();
}

<div id="small-dialog" class="zoom-anim-dialog mfp-hide">
    <div>
        <button title="Close (Esc)" type="button" class="mfp-close" style="position: static; margin-top: -18px;border:0px; float: left; margin-left: -29px;">@Resources.TCPResources.CloseText</button>
        <button title="Close (Esc)" type="button" class="mfp-close">@Resources.TCPResources.CloseText</button>
    </div>
    <div id="loadingSetView" class="">
    </div>
</div>
<div id="loading-div-background" class="hide">
    <div id="dvLoading">
        @*  <img style="height:80px;margin:30px;" src="images/loading.gif" alt="Loading.."/>*@
        <span style="color: black; font-weight: bold; font-size: 10px">Please wait....</span>
    </div>
</div>
<div id="hiddenfieldsdiv" class="hide">
    @Html.Hidden("hdnQuoteID", @Model.CategoriesPVM.QuoteID)
    @Html.Hidden("hdnPkgID", @Model.CategoriesPVM.SelectedGroupID)
    @Html.Hidden("hdnPageCount", @Model.CategoriesPVM.SelectedTitlesCount)
    @Html.Hidden("hdnCollectionPath", @Url.Action("AddCollectionsToQuotDWCartbyGroupID", "ItemListView"))
    <input type="hidden" id="hdnPageTitle" value="@ViewBag.Title" />
</div>
<div id="ViewItemConatiner" class="place-left body-text span12">
    @Html.Partial("../TCPViews/Partial/CategoriesItemViewPartial", Model.CategoriesPVM)
</div>

TPC.Web/Views/TCPViews/FAQ.cshtml
@model  TPC.Core.Models.FAQViewModel
@using TPC.Core.Models;
@using System.Configuration;
@{
    ViewBag.Title = Resources.TCPResources.MenuAboutUsforbreadcrumbs;
    Layout = "~/Views/Shared/PenworthyLayout.cshtml";
    int index = 0;
    string imagePath = ConfigurationManager.AppSettings["AboutUs"];
}

<div id="hiddenFiledsDiv" class="hide">
      <input type="hidden" id="hdnPageTitle" value="@ViewBag.Title" />
</div>
<div id="faq" class="span12 txt-Medium margin20 nlm nrm nbm">
    <div class="introductionTextSize">
        @Resources.TCPResources.AboutUsIntoductionText
    </div>
     <div class="padding15 nrp nlp">
        @foreach (FAQCategoriesViewModel FaqCat in Model.FAQCategories)
        {
            <div id="@FaqCat.Categories">
                <div class="largefont">
                    @{string categories = FaqCat.Categories == "FAQs" ? FaqCat.Categories : string.Empty;}
                    <strong>@categories</strong>
                </div>

                @{
            var lstQuestions = Model.FAQuestions.Where(e => e.FAQCategoryID == FaqCat.FAQCategoryID);
                }

                @foreach (var question in lstQuestions)
                {
                    index++;
                   
                    <div class="padding15 nrp nlp">
                        <div class="iconsize"><strong>@Html.Label(@question.FAQQuestion)</strong></div>
                         @if(index<6)
                    {
                     @*<img src="@Url.Content(@Resources.TCPResources.HomeSlideImagePath + index + ".jpg")" />*@
                          <img  src="~/Image/Getimage?id=@String.Format("{1}{0}{2}", index, imagePath,".jpg")">
                }
                        @{ var lstAnswers = Model.FAQAnswers.Where(e => e.FAQId == question.FAQId);  }
                        <div class="padding5">
                            @foreach (var answer in lstAnswers)
                            {
                               <div class="txt-Medium">@Html.Raw(@answer.FAQDetailedText)</div>
                            }
                        </div>
                    </div>
                }
            </div>
        }
            <a href="#">Back To Top</a>
      </div>
</div>

<div id="Prebound-dialog" class="zoom-anim-dialog  mfp-hide blackLineBorder marginLeft16">
        <button title="Close (Esc)" type="button" class="mfp-close">@Resources.TCPResources.CloseText</button>
        <div>
            <strong>@Resources.TCPResources.WhyPenworthyText</strong>
            <div class="place-left span9"><img style="height:500px" src="~/Images/Books-side-by-side.jpg" /></div>
            <div class="place-left span4 lnht26">
          @Resources.TCPResources.WhyPreboundDescText
            </div>
            <div class="place-left padding10">
                <div id="preboundBooks" class="place-left">
                <div id="preboundBooks" class="place-left span4"><img class="blog" src="~/Images/Better-Binding.jpg" /></div>
                <div id="preboundBooks" class="place-left span5"><img class="blog" src="~/Images/Library-Corners.jpg" /></div>
                <div id="preboundBooks" class="place-left span4"><img class="blog" src="~/Images/Rounded-Spines.jpg" /></div>
            </div>
            <div class="place-left">
            <a href="mailto:info@penworthy.com">Email us</a>  @Resources.TCPResources.PreboundEmailRequestText
                </div>
        </div>
    </div>
    </div>

TPC.Web/Views/TCPViews/GeneratePDF.cshtml
@model TPC.Core.Models.OrderViewModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
</head>
<body>
    @if (Model.Type == "Export")
    {
        @Html.Partial("../TCPViews/Partial/EmailPdfGeneration", Model)
    }
    else if (Model.Type == "invoicePdf")
	{
        @Html.Partial("../TCPViews/Partial/EmailInvoicePdfGeneration", Model)
	}
    else
    {
        @Html.Partial("../TCPViews/Partial/OrderHistoryPdfGeneration", Model)
    }
</body>
</html>

TPC.Web/Views/TCPViews/HelpwithyourDecisionWizardView.cshtml
@model TPC.Core.Models.BaseViewModel

@{
    ViewBag.Title = "Help with your Decision Wizard ®";
    Layout = "~/Views/Shared/PenworthyLayout.cshtml";
}

<table class="margintop28 span12">
    <tbody>
        <tr>
            <td class="text-center ">
                <video width="960" height="720" style="margin-left:-8px;" controls autoplay="autoplay">
                    <source src="@Url.Action("PlayVideoInfo","ItemListView")" type="video/mp4">
                </video>
            </td>
        </tr>
        @* <tr class="div-contentheight">
            <td>@Resources.TCPResources.YourDecision_WizardText </td>
        </tr>
        <tr class="div-contentheight">
            <td style="font-size:15px;"><strong>Here's a quick step-by-step:</strong></td>
        </tr>
        <tr>
            <td class="span12" style="border-bottom:1px solid black"></td>
        </tr>

        <tr class="div-contentheight">
            <td>@Resources.TCPResources.OneatatimeText</td>
        </tr>
        <tr class="div-contentheight">
            <td>
                <img src="~/Images/HelpDecisionWizard.png" /></td>
        </tr>
        <tr class="div-contentheight1">
            <td>@Resources.TCPResources.NewCategoryText</td>
        </tr>
        <tr class="div-contentheight">
            <td>
                <img src="~/Images/MyPenworthyDW.PNG" /></td>
        </tr>
        <tr class="div-contentheight">
            <td>@Resources.TCPResources.YesNoMayBeText</td>
        </tr>
        <tr class="div-contentheight">
            <td>
                <div class="place-left margin5 ntm nbm nlm">
                    <img src="~/Images/YesNoMaybe/MayBeNew.jpg" /></div>
                <div class="place-left  margin5 ntm nbm nlm">
                    <img src="~/Images/YesNoMaybe/NoNew.jpg" /></div>
                <div class="place-left margin5 ntm nbm nlm">
                    <img src="~/Images/YesNoMaybe/YesNew.jpg" /></div>
                <div class="place-left margin5 ntm nbm nlm">
                    <img src="~/Images/Arrow.PNG" /></div>
            </td>
        </tr>
        <tr class="div-contentheight1">
            <td>@Resources.TCPResources.YesTitleText</td>
        </tr>
        <tr class="div-contentheight">
            <td>
                <img src="~/Images/PenworthyLayout1.PNG" /></td>
        </tr>*@
    </tbody>
</table>

TPC.Web/Views/TCPViews/ItemListDetailedView.cshtml
@model TPC.Core.Models.ViewModels.ItemListDetailedViewModel

@using TPC.Core.Models.ViewModels;
<script type="text/javascript">
 $(document).ready(function () {
     
     //Javascript for updating the DW and Cart Count in content Page
     $('#SCItemCount sup').html('@Model.UserVM.CustomerInfoObj.DictCartDWItemsCount["SCItemsCount"]');
     $('#DWItemCount sup').html('@Model.UserVM.CustomerInfoObj.DictCartDWItemsCount["DWItemsCount"]');
 

     var AllCount=parseInt(@Model.noOfYesCount+@Model.noOfNoCount+@Model.noOfMaybeCount+@Model.noOfNewCount);
   
     var calcpercentage = String((parseInt(@Model.noOfYesCount) / parseInt(AllCount) * 100));
    
     var pb = $('#pb').progressbar();
     pb.progressbar('value', parseInt(calcpercentage));
    

       
        $('.button-set').click(function () {
              location.reload(true);
        });
        $('#divMenusCustRole').removeClass('hide').addClass('visible');
        $('#divMenusCustRole li').removeClass('navlihide active');
        $('#liItemListView').addClass('navlihide')
        $('#liItemDetailed').addClass('navlihide ');
        $('.navlihide').show();
        jQuery(document).ajaxStart(function () {

            $('#ItemListDetailedView').css({ "pointer-events": "none" });



        }).ajaxStop(function () {

            $('#ItemListDetailedView').css({ "pointer-events": "initial" });
        });
  })
 </script>
<div id="ItemListDetailedView">
<div id="pb" class="progress-bar span.caption" data-role="progress-bar" data-color="#99bfe6"></div>
<div id="loadingSetView">
   @{if(@Model.ItemDVM!=null)
     {
       Html.RenderPartial("../TCPViews/Partial/ItemDetailedPartial", new ViewDataDictionary(@Model.ItemDVM));
     }
     else{
       <label>No Items to display</label>
     }
       }

    </div>

</div>

TPC.Web/Views/TCPViews/ItemListView.cshtml
@model TPC.Core.Models.ItemListViewModel
@using TPC.Core.Models;
@using TPC.Core.Models.ViewModels;
@using TPC.Core.Interfaces;
@using TPC.Common.Enumerations;
@using TPC.Core;
@{
    
    ViewBag.Title = "ItemListView";


    // int NoOfPages = (int)Math.Ceiling((@Model.SelectionCount) / (double)Convert.ToInt32(Model.pageDenomination.Where(e => e.Selected == true).FirstOrDefault().ItemValue));
    IItemListViewService _itemListServ = new ItemListViewService();
    if (Model.QuoteTitle != null && Model.QuoteType != null)
    {
        // ViewData["QuoteTitle"] = Model.QuoteTitle;
        // ViewData["QuoteType"] = Model.QuoteType;
        ViewData["QuoteID"] = Model.QuoteID;
        ViewData["Type"] = Model.KPLItemListVM != null && Model.KPLItemListVM.Count() > 0 ? Model.KPLItemListVM.FirstOrDefault().QuoteFlag: string.Empty;
    }
   
}


<div id="hiddenfieldsdiv" class="hide">
    @Html.Hidden("hdnQuoteID", @Model.QuoteID)
    @Html.Hidden("hdnGroupID", @Model.GroupID)
    @Html.Hidden("hdnCurrentPageIndex", Model.currentPageIndex)
    @Html.Hidden("hdnSelectionCount", Model.SelectionCount)
    @Html.Hidden("hdnYesCount", Model.noOfYesCount)
    @Html.Hidden("hdnNoCount", Model.noOfNoCount)
    @Html.Hidden("hdnMayBeCount", Model.noOfMaybeCount)
    @Html.Hidden("hdnNewCount", Model.noOfNewCount)
    <input type="hidden" id="hdnViewDataGroupID" value="@ViewData["GroupID"]"/>
    <input type="hidden" id="hdnQuoteType" value="@ViewData["QuoteType"]"/>
    <input type="hidden" id="hdnPageTitle" value="@ViewBag.Title" />
    <input type="hidden" id="hdnPageType" value="@ViewData["Type"]" />
</div>
<div id="onScreen-dialog" class="zoom-anim-dialog mfp-hide">
      <div>
     <button title="Close (Esc)" type="button" class="mfp-close" style="position:static; margin-top: -26px;float: left;margin-left: -29px;">@Resources.TCPResources.CloseText</button>
    <button title="Close (Esc)" type="button" class="mfp-close">@Resources.TCPResources.CloseText</button>
        </div>
    <div id="loadingSetView" class="">
    </div>
</div>

<div id="divMain" class="metro margin20 nlm nrm nbm">
    @Html.Partial("../TCPViews/Partial/ItemListViewPartial", @Model)
</div>

TPC.Web/Views/TCPViews/UpdateCollection.cshtml
@model TPC.Core.Models.Models.CategoryItemGroupModel
@using TPC.Core.Models.Models;
@{
    ViewBag.Title = Resources.TCPResources.UpdateCollectionText;
    Layout = "~/Views/Shared/PenworthyLayout.cshtml";
}
<input type="hidden" id="hdnPageTitle" value="@ViewBag.Title" />
<div id="Collection" class="border span5 place-left place-left">
     @Html.Partial("../TCPViews/Partial/UpdateCollectionPartial",Model.lstFilterModel)
</div>



}
<div id="UpdateSelectedCollection" class="border span575 place-left text-center place-left" style="">
    @Html.Partial("../TCPViews/Partial/UpdateExistingCollectionPartial",new FilterModel())
</div>
@*<div class="border span575 place-left text-right place-left" style="height:500px;">
    
</div>*@