TPC.Web/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using System.Web.UI;

namespace TPC.Web.Controllers
{
    public class ImageController : Controller
    {
        [AllowAnonymous]
        public ActionResult GetImage(string Id)
        {
            HttpContext.Response.Cache.SetCacheability(HttpCacheability.Public);
            HttpContext.Response.Cache.SetExpires(Cache.NoAbsoluteExpiration);
            HttpContext.Response.Cache.SetLastModifiedFromFileDependencies();

            string imagePath = ConfigurationManager.AppSettings["CommonRepository"];
            if (!Id.Contains(imagePath))
                imagePath = imagePath + Id;
            else
                imagePath = Id;
            if (!System.IO.File.Exists(imagePath))
            {
                string ext = imagePath.Substring(imagePath.LastIndexOf(".") + 1);
                imagePath = imagePath.Substring(0, imagePath.LastIndexOf("."));
                imagePath = imagePath + ".jpeg";
            }

            return File(imagePath, "image/jpeg");
        }

        [AllowAnonymous]
        public ActionResult GetPdf(string path)
        {
            HttpContext.Response.Cache.SetCacheability(HttpCacheability.Public);
            HttpContext.Response.Cache.SetExpires(Cache.NoAbsoluteExpiration);
            HttpContext.Response.Cache.SetLastModifiedFromFileDependencies();
            
            if (!System.IO.File.Exists(path))
            {
                path=path.Replace("_DUP","");
            }
            return File(path, "application/pdf");
        }
    }
}

TPC.Web/Controllers/TCPControllers/PartialControllers/ItemContainerPartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TPC.Core.Models;
using TPC.Web.Filters;
using TPC.Core;
using TPC.Common.Enumerations;
using TPC.Core.Interfaces;
using Microsoft.Practices.Unity;
using System.Reflection;
using TPC.Core.Models.Models;
using TPC.Core.Models.ViewModels;
using System.Web.UI;
using WebMatrix.WebData;
using System.Web.UI.WebControls;
using System.IO;
using System.Configuration;

namespace TPC.Web.Controllers
{

    [TPCAuthorize]

    public class ItemContainerPartialController : BaseController
    {

        private readonly IItemContainerService _itemcontainerPartialSrv;
        private readonly IUserPreferenceService _iUserPreferenceSrv;

        public ItemContainerPartialController(ItemContainerService ItemContainerSrv)
        {
            _itemcontainerPartialSrv = ItemContainerSrv;
            _iUserPreferenceSrv = new UserPreferenceService();


        }
        //
        // GET: /ItemContainerPartial/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewEditQuote(string quoteDWID, string type)
        {
            IQuoteViewService _QuoteViewSrv = new QuoteViewService();
            ViewData["QuoteID"] = quoteDWID;
            ViewData["QuoteType"] = _QuoteViewSrv.getQuoteTypeText(Convert.ToInt32(quoteDWID));
            ViewData["QuoteTitle"] = _QuoteViewSrv.getQuoteTitleText(Convert.ToInt32(quoteDWID));
            return ItemContainer(quoteDWID, type);
        }

        public ActionResult ItemContainer(FormCollection activeQuoteVM)
        {
            IQuoteViewService _QuoteViewSrv = new QuoteViewService();
            IShoppingCartService _shoppingCartSrv = new ShoppingCartService();
            IItemListViewService _iItemListViewService = new ItemListViewService();
            _QuoteViewSrv.UserVM = UserVM;

            string selectedQuoteID = string.Empty;
            string quotetypeText = "";

            if (activeQuoteVM != null)
            {
                if (activeQuoteVM.GetValues("assignChkBx") != null)
                {
                    selectedQuoteID = activeQuoteVM.GetValues("assignChkBx").FirstOrDefault().Split('%')[0];
                    quotetypeText = activeQuoteVM.GetValues("assignChkBx").FirstOrDefault().Split('%')[1];
                    string totalItems = activeQuoteVM.GetValues("assignChkBx").FirstOrDefault().Split('%')[2];
                    string price = activeQuoteVM.GetValues("assignChkBx").FirstOrDefault().Split('%')[3];
                    ViewData["QuoteType"] = quotetypeText;
                    ViewData["QuoteTitle"] = _QuoteViewSrv.getQuoteTitleText(Convert.ToInt32(selectedQuoteID));
                    ViewData["QuoteID"] = selectedQuoteID;
                    ViewData["SearchCategory"] = quotetypeText;
                }
            }

            //Added for Exception when no Quotes are present
            if (selectedQuoteID == string.Empty)
            {
                selectedQuoteID = activeQuoteVM["DWQuoteID"];
            }

            //For Active Quote View
            if (activeQuoteVM["View"] != null)
            {
                return ItemContainer(selectedQuoteID, "View");
            }

            //For DW View
            if (activeQuoteVM["DWView"] != null)
            {
                _shoppingCartSrv.UserVM = UserVM;
                ShoppingCartViewModel scVM = _shoppingCartSrv.GetDWByClientID(UserVM.CRMModelProperties.LoggedINCustomerUserID.ToString(), Convert.ToInt32(selectedQuoteID));
                UserVM.SearchCategory = string.Empty;
                this.AssignUserVM(scVM.UserVM);
                return View("../TCPViews/RepoDecisionWizard", scVM);
            }
            //For Dw//Active Quote Filter View
            if (activeQuoteVM["Category"] != null)
            {
                return ItemContainer(selectedQuoteID, "Category");
            }
            //For Preview of DW
            if (activeQuoteVM["DetailList"] == Resources.TCPResources.DetailList)
            {
                ViewData["GroupName"] = activeQuoteVM["DetailList"];
                _iItemListViewService.UserVM = UserVM;
                _QuoteViewSrv.UserVM = UserVM;
                ItemListViewModel itmLstVM = _iItemListViewService.GetDWItemsList(Convert.ToInt32(ViewData["QuoteID"]), Resources.TCPResources.DetailList, "10", 0,"");
                itmLstVM.KPLItemListVM.ForEach(t => t.IsListView = true);
                itmLstVM.IsListView = true;
                this.AssignUserVM(itmLstVM.UserVM);
                return View("../TCPViews/CustDecisionWizardView", itmLstVM);
            }
            //Default is for KPL-Item List
            return ItemContainer(selectedQuoteID, "KPL");
        }

        //[OutputCache(CacheProfile = "Aggressive", VaryByHeader = "X-Requested-With", Location = OutputCacheLocation.Any, NoStore = true)]
        private ActionResult ItemContainer(string quoteID, string type)
        {
            IQuoteViewService _QuoteViewSrv = new QuoteViewService();
            _QuoteViewSrv.UserVM = UserVM;
            _itemcontainerPartialSrv.UserVM = UserVM;

            if (type == "View")
            {
                ViewData["SearchCategory"] = _QuoteViewSrv.getQuoteTypeText(Convert.ToInt32(quoteID));
                QuoteViewModel qVM = _QuoteViewSrv.GetQuoteView(Convert.ToInt32(quoteID));
                UserVM.SearchCategory = string.Empty;
                this.AssignUserVM(qVM.UserVM);
                return View("../TCPViews/QuoteView", qVM);
            }

            ViewData["QuoteID"] = quoteID;
            if (type == "Category")
            {
                CategoriesItemContainerViewModel categoriesItemCVM = new CategoriesItemContainerViewModel();
                categoriesItemCVM.UserVM = UserVM;
                string noofItemsPerPage = "60";
                categoriesItemCVM = _itemcontainerPartialSrv.GetSelectedCollectionItem((int)GroupEnum.EntirePenworthyCollection, 1, noofItemsPerPage, Convert.ToInt32(quoteID), "");
                this.AssignUserVM(categoriesItemCVM.UserVM);
                return View("../TCPViews/CategoriesItemContainer", categoriesItemCVM);
            }

            KPLItemConatinerViewModel ciCVM = new KPLItemConatinerViewModel();
            ciCVM.UserVM = UserVM;
            ciCVM = _itemcontainerPartialSrv.FillItemDetails(quoteID, type);
            this.AssignUserVM(ciCVM.UserVM);

            return View("../TCPViews/KPLItemContainer", ciCVM);
        }


        public ActionResult ViewSelectedGroupItemList(int quoteID, string quoteType)
        {
            ViewData["QuoteType"] = quoteType;
            _itemcontainerPartialSrv.UserVM = UserVM;
            return View("../TCPViews/CategoriesItemContainer", _itemcontainerPartialSrv.GetItemContainerVM(quoteID));
        }

        public ActionResult ViewQuoteandDecisionWizard(string quoteID, string quoteType)
        {
            IQuoteViewService _QuoteViewSrv = new QuoteViewService();
            _QuoteViewSrv.UserVM = UserVM;

            ViewData["QuoteType"] = quoteType;
            ViewData["QuoteID"] = quoteID;
            ViewData["QuoteTitle"] = _QuoteViewSrv.getQuoteTitleText(Convert.ToInt32(quoteID));

            IShoppingCartService _shoppingCartSrv = new ShoppingCartService();
            _shoppingCartSrv.UserVM = UserVM;

            if (quoteType == @Resources.TCPResources.DecisionWizardliText)
            {
                UserVM.SearchCategory = string.Empty;
                ShoppingCartViewModel scVM = _shoppingCartSrv.GetDWByClientID(UserVM.CRMModelProperties.LoggedINCustomerUserID.ToString(), Convert.ToInt32(quoteID));
                this.AssignUserVM(scVM.UserVM);
                return View("../TCPViews/RepoDecisionWizard", scVM);
            }

            if (quoteType == @Resources.TCPResources.ShoppingCartliText)
            {
                return View("../TCPViews/ShoppingCart", _shoppingCartSrv.GetShoppingCartViewByClientID(UserVM.CRMModelProperties.LoggedINCustomerUserID));
            }

            int quoteid = Convert.ToInt32(quoteID);
            if (quoteID != null)
            {
                UserVM.SearchCategory = string.Empty;
                this.AssignUserVM(_QuoteViewSrv.UserVM);
                return View("../TCPViews/QuoteView", _QuoteViewSrv.GetQuoteView(quoteid));
            }
            else
            {
                UserVM.SearchCategory = string.Empty;
                this.AssignUserVM(_QuoteViewSrv.UserVM);
                return View("../TCPViews/QuoteView", _QuoteViewSrv.GetQuoteView(UserVM.CurrentQuoteID));
            }
        }


        [HttpPost]
        public string DeleteItemFromQuote(string quoteID, string itemID,string type="")
        {
            _itemcontainerPartialSrv.UserVM = UserVM;
            _itemcontainerPartialSrv.DeleteItemFromQuote(Convert.ToInt32(quoteID), itemID,type);
            this.AssignUserVM(_itemcontainerPartialSrv.UserVM);
            return itemID;
        }

        public ActionResult ItemContainerDetails(string quoteID, string quoteType, string type)
        {
            IQuoteViewService _QuoteViewSrv = new QuoteViewService();
            ViewData["QuoteType"] = _QuoteViewSrv.getQuoteTypeText(Convert.ToInt32(quoteID));
            ViewData["QuoteTitle"] = _QuoteViewSrv.getQuoteTitleText(Convert.ToInt32(quoteID));
            ViewData["QuoteID"] = quoteID;
            ViewData["SearchCategory"] = ViewData["QuoteType"];
            return ItemContainer(quoteID, type);

        }
        [AllowAnonymous]
        public ActionResult GetSelectedCollectionPaginationItem(int groupID, int currentPageIndex, string noofItemsPerPage, string selectedPackageIdsList = "", int quoteID = 0)
        {

TPC.Web/Controllers/TCPControllers/PartialControllers/ItemDetailedPartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TPC.Core.Interfaces;
using TPC.Web.Filters;

namespace TPC.Web.Controllers.TCPControllers.PartialControllers
{
    [TPCAuthorize]
 
    public class ItemDetailedPartialController : BaseController
    {
        //
        // GET: /ItemDetailedPartial/
        private readonly IItemService _itemservice;
        public ItemDetailedPartialController(IItemService itemService)
        {
            _itemservice = itemService;
            _itemservice.UserVM = UserVM;
        }

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ItemDetail(string itemID, int QuoteID)
        {

            return PartialView("../TCPViews/Partial/ItemDetailedPartial", _itemservice.GetItemListDetailByID(itemID, QuoteID.ToString()));
        }

       

    }
}

TPC.Web/Views/TCPViews/Partial/CollectionsItemsPartial.cshtml
@model TPC.Core.Models.ItemGroupViewModel
@using TPC.Core.Models;
@using TPC.Core.Models.ViewModels;
@using TPC.Common.Enumerations;
@using System.Configuration;
@{
    int noofRowsPerpage;
    int noofColumns = ViewBag.Title == "Search" || ViewBag.TiTle == Resources.TCPResources.ItemListViewText ? 5 : 4;
    int noofRecords = Model.ItemPVM != null && Model.ItemPVM.ListItemVM.Count() > 0 ? Model.ItemPVM.ListItemVM.Count() : 60;
    noofRowsPerpage = (int)Math.Ceiling(noofRecords / (double)noofColumns);
    string currentDisplaytext = Model.ItemPVM != null && Model.ItemPVM.ListItemVM.Count() > 0 ? Model.ItemPVM.ListItemVM.FirstOrDefault().QuoteTypeText == @Resources.TCPResources.DecisionWizardliText ? "DW" :
       (Model.ItemPVM.ListItemVM.FirstOrDefault().QuoteTypeText == @Resources.TCPResources.ShoppingCartText1 || Model.ItemPVM.ListItemVM.FirstOrDefault().QuoteTypeText == "" ? "Cart" : "Quote") : "Cart";
    string imagePath = ConfigurationManager.AppSettings["ImagesH135"];
    string divgroupwidth = ViewBag.Title == "Search" || ViewBag.TiTle == Resources.TCPResources.ItemListViewText ? "925px" : "740px";
    int columnCount = ViewBag.Title == "Search" || ViewBag.TiTle == Resources.TCPResources.ItemListViewText ? 4 : 3;
    int itemCount = ViewBag.Title == "Search" || ViewBag.TiTle == Resources.TCPResources.ItemListViewText ? 5 : 4;
    string ARlevel = string.Empty;
    string dwDateText = string.Empty;
}

<div id="dvSet-1" class="place-left margin20 ntm nbm span9_35">
    @{
        ItemGroupViewModel itemGVM = Model;
        int columnsCount = 0;
    }
    @if (Model.ItemPVM != null)
    {
        for (int irows = 0; irows < @noofRowsPerpage; irows++)
        {
        <div id="@irows" class="place-left margin20 nlm nrm" style="width:@divgroupwidth">
            @for (int icolumns = 0; icolumns < @noofColumns; icolumns++)
            {
                if ((columnsCount + icolumns) >= itemGVM.ItemPVM.ListItemVM.Count())
                {
                    columnsCount = itemGVM.ItemPVM.ListItemVM.Count() - 1;
                    irows = noofRowsPerpage;
                    icolumns = itemCount;
                    break;
                }
                ItemViewModel obj = Model.ItemPVM.ListItemVM[columnsCount + icolumns];
                <div id="Item" class="body-text ntm nbm place-left">
                    @{
                // string classname = @obj.IsInCustomerTitles == true ? "div-bgopacity" : "";
                // string disableStatus = @obj.IsPreviewItem == false ? "div-bgopacity div-filterdisable" : "";
                string disableStatus = @obj.IsPreviewItem == false ? "div-bgopacity div-filterdisable opacityz-index" : "";
                string starPositionStatus = ViewBag.Title == "HomePage" ? "style=margin-left:-4px" : "";
                    }
                    <div id="ViewDetailItem-@itemGVM.GroupID-@icolumns" data-Title="@obj.IsInCustomerTitles"  class="@disableStatus collectionitemImgWidth  margin20  nlm ntm nbm place-left">
                        @*  <div id="ViewDetailItem-@itemGVM.GroupID-@icolumns" data-Title="@obj.IsInCustomerTitles"  class="@disableStatus  opacityz-index collectionitemImgWidth  margin20  nlm ntm nbm place-left">*@
                        <div id="@obj.ItemID" class="place-left collectionitemImgWidth text-center">
                            <div id="divCartStatus-@obj.ItemID-@icolumns" class="divCartStatus-@obj.ItemID">
                                @if (Request.IsAuthenticated)
                                {
                                    if (@obj.IsInSCDWQuote == true)
                                    {
                                    <div id="carttext-@obj.ItemID" class="carttext-@obj.ItemID">
                                        @if (obj.IsInCustomerTitles == true)
                                        {
                                            <i class="icon-star-3 fg-yellow itemTextSize imgstar yellowstar3 z-index"></i>
                                        }
                                        else if ((obj.SeriesBroughtBefore == true || obj.CharecterBroughtBefore == true))
                                        {
                                            <i class="icon-star-3 button-fg itemTextSize imgstar yellowstar3 z-index"></i>
                                        }
                                        &nbsp;In @currentDisplaytext
                                    </div>
                                    <div id="carttextlink-@obj.ItemID" class="carttextlink-@obj.ItemID hide">
                                        @if (obj.IsInCustomerTitles == true)
                                        {
                                            <i class="icon-star-3 fg-yellow itemTextSize imgstar yellowstar3 z-index"></i>
                                        }
                                        else if ((obj.SeriesBroughtBefore == true || obj.CharecterBroughtBefore == true))
                                        {
                                            <i class="icon-star-3 button-fg itemTextSize imgstar yellowstar3 z-index"></i>
                                        }
                                        <button id="1" name="1" value="1" data-itemid="@obj.ItemID" class="AddCart itemTextSize" style="background-color:white;color:#2e92cf;padding:0px;font-family:'Segoe UI_','Open Sans',Verdana,Arial,Helvetica,sans-serif;margin-right:14px;" >Add To @currentDisplaytext</button>
                                    </div>
                                    }
                                    else
                                    {
                                    <div id="carttext-@obj.ItemID" class="hide carttext-@obj.ItemID">
                                        @if (obj.IsInCustomerTitles == true)
                                        {
                                            <i class="icon-star-3 fg-yellow itemTextSize imgstar yellowstar3 z-index"></i>
                                        }
                                        else if ((obj.SeriesBroughtBefore == true || obj.CharecterBroughtBefore == true))
                                        {
                                            <i class="icon-star-3 button-fg itemTextSize imgstar yellowstar3 z-index"></i>
                                        }
                                        &nbsp;In @currentDisplaytext
                                    </div>
                                    <div id="carttextlink-@obj.ItemID" class="carttextlink-@obj.ItemID">
                                        @if (obj.IsInCustomerTitles == true)
                                        {
                                            <i class="icon-star-3 fg-yellow itemTextSize imgstar yellowstar3 z-index"></i>
                                        }
                                        else if ((obj.SeriesBroughtBefore == true || obj.CharecterBroughtBefore == true))
                                        {
                                            <i class="icon-star-3 button-fg itemTextSize imgstar yellowstar3 z-index"></i>
                                        }
                                        <button id="1" name="1" value="1" data-itemid="@obj.ItemID" class="AddCart itemTextSize" style="background-color:white;color:#2e92cf;padding:0px;font-family:'Segoe UI_','Open Sans',Verdana,Arial,Helvetica,sans-serif;margin-right:14px;" >Add To @currentDisplaytext</button>
                                    </div>
                                    }
                                }
                                else
                                {
                                    <a class="popup-with-zoom-anim login carouselCartText" href="#small-dialog">Add To Cart</a>
                                }
                            </div>
                        </div>
                        <div id="divImg-@itemGVM.GroupID-@icolumns" class="collectionitemImgWidth place-left text-center divImg-@itemGVM.GroupID">
                            <a title="@obj.ItemID" class="popup-with-zoom-anim ItemDetailSeries" href="#small-dialog" >
                                <img id="@obj.ItemID" class="imgTest-@obj.ItemID-@icolumns titleShadow" src="~/Image/Getimage?id=@String.Format("{1}{2}{0}{3}", @obj.ISBN, imagePath, "\\", ".jpg")">
                                @*   <img id="@obj.ItemID" class="imgTest-@obj.ItemID-@icolumns titleShadow" src="@Url.Action("Getimage","Image", new {id =@imagePath + obj.ISBN + ".jpg" })" />*@
                                @* @Html.Action("Index", "Image")*@
                            </a>

                        </div>

                        <div class="collectionitemImgWidth itemTextSize place-left text-center">
                            @obj.Title
                        </div>
                        <div id="divGradePrice-@itemGVM.GroupID-@icolumns" class="collectionitemImgWidth itemTextSize place-left text-center divImg-@itemGVM.GroupID">
                            @if (Roles.IsUserInRole(UserRolesEnum.Repo.ToString()) == true && ViewBag.Title != "Search")
                            {
                                <span>@string.Format("{0:C2}", obj.IPrice) </span>
                                ARlevel = obj.ARLevel != string.Empty ? "," + obj.ARLevel : string.Empty;

                            }
                            else { ARlevel = obj.ARLevel; }
                            @if (string.IsNullOrEmpty(ARlevel) && string.IsNullOrEmpty(obj.RCLevel))
                            {
                                <br />
                            }
                            else
                            {
                                @ARlevel  @obj.RCLevel
                            }
                            <input type="checkbox" id="chkItem" class="group1 hide" data-price="@obj.IPrice" value="@obj.ItemID" checked="@obj.IsSelected"/>
                        </div>
                        <div class="collectionitemImgWidth itemTextSize place-left text-center">
                            @{dwDateText = string.Empty;}
                            @if (!string.IsNullOrEmpty(obj.DWDate))
                            {
                                dwDateText = "LDW:" + obj.DWDate;
                            }
                            @if (currentDisplaytext == "DW")
                            {
                                <span id="ldwText-@obj.ItemID">@dwDateText</span>
                            }

                        </div>
                    </div>
                </div>
                            if (icolumns == columnCount)
                            {
                                columnsCount += (@icolumns + 1);
                            }
            }

        </div>
        }
    }
</div>

TPC.Web/Views/TCPViews/Partial/CustDecisionWizardPartialView.cshtml
@model TPC.Core.Models.ItemListViewModel
@using TPC.Core.Models;
@using TPC.Core.Models.ViewModels;
@using TPC.Core.Interfaces;
@using TPC.Common.Enumerations;
@using TPC.Core;
@{
    ViewBag.Title = "ItemListView";
}
<script type="text/javascript">
    function DeleteNoItemsSucess(data) {
        window.location.reload();
        }
</script>
<div id="displayItems" class="place-left span12 ">
    <div id="divStatusList" class="span12 place-left contentTextSmall" style="position: fixed; z-index: 1; margin-top: -12px;">
        <table id="tblStatusList" class="span12 ">
            <tr>
                <td>
                    @if (Model.QuoteType == Resources.TCPResources.DecisionWizardliText && Model.IsListView == true)
                    {
                        <div id="pb1" class="progress-bar custom-progress-bar" data-role="progress-bar" data-color="#99bfe6"></div>
                    }
                </td>
            </tr>
            <tr>
                <td colspan="3">
                        <div id="goldStarText" class="place-left margin10 nlm nbm ">
                            <i id="staricon-yellow" class="icon-star-3 margin5 ntm nbm nlm fg-yellow itemTextSize"></i>@Resources.TCPResources.goldStarText
                        </div>
                        <div class="place-left margin10 nbm ">
                            <i id="staricon-blue" class="icon-star-3 margin5 ntm nbm nlm button-fg itemTextSize"></i>@Resources.TCPResources.BlueStarText
                        </div>
                </td>
            </tr>
           
            <tr>
                <td>
                    <div id="divStatus" class="span6_5 place-left contentTextSmall" style="margin-top: -6px;">
                        @if (Model.QuoteType == Resources.TCPResources.DecisionWizardliText && Model.IsListView == true)
                        {
                            <table id="tblStatus" class="span6_5 margin10 nlm nrm">
                                <tr>
                                    <td style="width: 17px">
                                        <input type="checkbox" name="group2" class="SelectAll" data-count="@Convert.ToInt32(@Model.noOfYesCount + @Model.noOfNoCount + @Model.noOfMaybeCount + @Model.noOfNewCount)" value="0">
                                    </td>
                                    <td style="width: 53px">
                                        <label class="place-left LableHdTD ">All</label>
                                        <label class="place-left lableValTD" id="0">(@Convert.ToInt32(@Model.noOfYesCount + @Model.noOfNoCount + @Model.noOfMaybeCount + @Model.noOfNewCount))</label>
                                    </td>
                                    <td style="width: 17px">
                                        <input type="checkbox" name="group2" class="case" value="1" data-count="@Model.noOfYesCount">
                                    </td>
                                    <td>
                                        <label class="place-left LableHdTD">Yes</label>
                                        <label class="place-left lableValTD" id="1">(@Model.noOfYesCount)</label>
                                        <label class="place-left LableHdTD">&nbsp;Price&nbsp; </label>
                                        <label class="place-left LableHdTD" id="lblYesPrice">@String.Format("{0:C}", Model.YesTotalPrice)</label>
                                    </td>

                                    <td style="width: 17px">
                                        <input type="checkbox" name="group2" class="case" value="2" data-count="@Model.noOfNoCount">
                                    </td>
                                    <td style="width: 53px">
                                        <label class="place-left LableHdTD">No</label>
                                        <label class="place-left lableValTD" id="2">(@Model.noOfNoCount)</label>
                                    </td>
                                    <td style="width: 17px">
                                        <input type="checkbox" name="group2" class="case" value="3" data-count="@Model.noOfMaybeCount">
                                    </td>
                                    <td style="width: 76px">
                                        <label class="place-left LableHdTD">Maybe</label>
                                        <label class="place-left lableValTD" id="3">(@Model.noOfMaybeCount)</label>
                                    </td>

                                    <td style="width: 17px">
                                        <input type="checkbox" name="group2" class="case" value="5" data-count="@Model.noOfNewCount">
                                    </td>
                                    <td style="width: 59px">
                                        <label class="place-left LableHdTD">New</label>
                                        <label class="place-left lableValTD" id="5">(@Model.noOfNewCount)</label>
                                    </td>
                                </tr>
                            </table>
                        }
                        else
                        {
                            <a href="@Url.Action("Index", "Home")">Back To Home</a>
                        }
                    </div>
                </td>
                <td>
                    <div class=" place-right span6 margin10 ntm nbm nrm">
                        @if (Model.IsListView)
                        {
                            <input type="button" id="btnviewOne" class="text-right place-right" value="View One" style="background-color: transparent">
                            using (Ajax.BeginForm("DeleteNoItemsByQuoteID", "ItemContainerPartial", new { quoteID = Model.QuoteID }, new AjaxOptions { HttpMethod = "POST", OnSuccess = "DeleteNoItemsSucess", UpdateTargetId = "UpdateSelectedCollection", LoadingElementId = "loader" }, new { enctype = "multipart/form-data", @style = "margin:0px" }))
                            {
                                <input type="submit" id="btnDeleteNoTitles" class="text-right place-right margin-right22" value="Delete No Titles" style="background-color: transparent">
                            }
                        }
                        else
                        {
                            <input type="button" id="btnviewAll" class="text-right place-right" value="View All" style="background-color: transparent">
                        }
                    
                         
                    </div>
                </td>
                <td class="place-right span3">

                    <div class=" place-right span3">
                    </div>

                </td>
            </tr>
        </table>
            <div id="text" class="hide margin5 nlm nrm nbm"></div>
    </div>
    <div id="divCollectionDW" class="paddingtop30">
        @Html.Partial("../TCPViews/Partial/CollectionsDWItemsPartial", @Model.ItemGroupViewM)
    </div>
</div>